on:
  push:
    branches: [ release/*, 'hotfix/*' ]
  workflow_dispatch:

jobs:
  pre-release:
    uses: abbgrade/PsBuildTasks/.github/workflows/pre-release-windows.yml@1.8.2
    with:
      module-name: PsSqlClient
    secrets:
      ps-gallery-key: ${{ secrets.PS_GALLERY_KEY }}
